In [1]:
import pandas as pd


In [2]:
df_m=pd.read_csv('D:\iNeuron\Intership_1\Absenteeism_at_work_AAA\Merge1.csv')

In [3]:
df_m.head()

Unnamed: 0  ID  Reason for absence  Month of absence  Day of the week  \
0           0  11                  26                 7                3   
1           1  11                  26                10                4   
2           2   1                  26                12                4   
3           3  20                  26                12                6   
4           4  20                  26                 3                2   

   Seasons  Transportation expense  Distance from Residence to Work  \
0        1                     289                               36   
1        4                     289                               36   
2        4                     235                               11   
3        4                     260                               50   
4        2                     260                               50   

   Service time  Age  ...  Social smoker  Pet  Weight  Height  \
0            13   33  ...              0    1      90     172   
1            13   33  ...              0    1      90     172   
2            14   37  ...              0    1      88     172   
3            11   36  ...              0    0      65     168   
4            11   36  ...              0    0      65     168   

   Body mass index  Absenteeism time in hours  Reason_Code  \
0               30                          4           26   
1               30                          8           26   
2               29                          8           26   
3               23                          8           26   
4               23                         16           26   

                Reason      Reason_Original  Absnt_hr_estimate  
0  Unjustified Absence  Unjustified Absence            2-4 hrs  
1  Unjustified Absence  Unjustified Absence            4-8 hrs  
2  Unjustified Absence  Unjustified Absence            4-8 hrs  
3  Unjustified Absence  Unjustified Absence            4-8 hrs  
4  Unjustified Absence  Unjustified Absence           8-24 hrs  

[5 rows x 26 columns]

In [4]:
df_m.columns

Index(['Unnamed: 0', 'ID', 'Reason for absence', 'Month of absence',
       'Day of the week', 'Seasons', 'Transportation expense',
       'Distance from Residence to Work', 'Service time', 'Age',
       'Work_load_Average_day', 'Hit target', 'Disciplinary failure',
       'Education', 'Son', 'Social drinker', 'Social smoker', 'Pet', 'Weight',
       'Height', 'Body mass index', 'Absenteeism time in hours', 'Reason_Code',
       'Reason', 'Reason_Original', 'Absnt_hr_estimate'],
      dtype='object')

In [5]:
df_m.drop('Unnamed: 0',axis=1)

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0    11                  26                 7                3        1   
1    11                  26                10                4        4   
2     1                  26                12                4        4   
3    20                  26                12                6        4   
4    20                  26                 3                2        2   
..   ..                 ...               ...              ...      ...   
735  15                   3                 1                4        2   
736  18                   2                11                4        4   
737  17                  16                 4                3        3   
738  25                  16                 4                3        3   
739  17                  16                 5                6        3   

     Transportation expense  Distance from Residence to Work  Service time  \
0                       289                               36            13   
1                       289                               36            13   
2                       235                               11            14   
3                       260                               50            11   
4                       260                               50            11   
..                      ...                              ...           ...   
735                     291                               31            12   
736                     330                               16             4   
737                     179                               22            17   
738                     235                               16             8   
739                     179                               22            17   

     Age  Work_load_Average_day  ...  Social smoker  Pet  Weight  Height  \
0     33                239.554  ...              0    1      90     172   
1     33                253.465  ...              0    1      90     172   
2     37                261.306  ...              0    1      88     172   
3     36                261.306  ...              0    0      65     168   
4     36                343.253  ...              0    0      65     168   
..   ...                    ...  ...            ...  ...     ...     ...   
735   40                330.061  ...              0    1      73     171   
736   28                268.519  ...              0    0      84     182   
737   40                246.288  ...              1    0      63     170   
738   32                246.288  ...              0    0      75     178   
739   40                237.656  ...              1    0      63     170   

     Body mass index  Absenteeism time in hours  Reason_Code  \
0                 30                          4           26   
1                 30                          8           26   
2                 29                          8           26   
3                 23                          8           26   
4                 23                         16           26   
..               ...                        ...          ...   
735               25                          8            3   
736               25                         24            2   
737               22                          2           16   
738               25                          3           16   
739               22                          1           16   

                                                Reason  \
0                                  Unjustified Absence   
1                                  Unjustified Absence   
2                                  Unjustified Absence   
3                                  Unjustified Absence   
4                                  Unjustified Absence   
..                                                 ...   
735                          Diseases Related to blood   
736                  

In [6]:
df_m_1=df_m[['Reason for absence','Transportation expense','Distance from Residence to Work','Age','Body mass index','Absnt_hr_estimate']]

In [7]:
df_m_1.head()

Reason for absence  Transportation expense  \
0                  26                     289   
1                  26                     289   
2                  26                     235   
3                  26                     260   
4                  26                     260   

   Distance from Residence to Work  Age  Body mass index Absnt_hr_estimate  
0                               36   33               30           2-4 hrs  
1                               36   33               30           4-8 hrs  
2                               11   37               29           4-8 hrs  
3                               50   36               23           4-8 hrs  
4                               50   36               23          8-24 hrs

In [8]:
#Renaming reason code as column to make it simpler and cosume less space..encodig plans
df_m_1.rename(columns={'Reason for absence':'R_code','Distance from Residence to Work':'Office Distance'},inplace=True)

C:\Users\subra\Anaconda3\lib\site-packages\pandas\core\frame.py:4298: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [9]:
df_m_1.head()

R_code  Transportation expense  Office Distance  Age  Body mass index  \
0      26                     289               36   33               30   
1      26                     289               36   33               30   
2      26                     235               11   37               29   
3      26                     260               50   36               23   
4      26                     260               50   36               23   

  Absnt_hr_estimate  
0           2-4 hrs  
1           4-8 hrs  
2           4-8 hrs  
3           4-8 hrs  
4          8-24 hrs

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [11]:
#onehot_encoder=OneHotEncoder(sparse=False,categorical_features=[0])
#onehot_encoded=onehot_encoder.fit_transform(df_m_1['R_code'].values.reshape(-1,1))

Above will no longer working have to use column transformer

In [12]:
#print(onehot_encoded)

In [13]:
#print(onehot_encoder.transform(np.array([26]).reshape(-1,1)))

In [14]:
#onehot_encoder.categories_

In [15]:
df_m_1.head()

R_code  Transportation expense  Office Distance  Age  Body mass index  \
0      26                     289               36   33               30   
1      26                     289               36   33               30   
2      26                     235               11   37               29   
3      26                     260               50   36               23   
4      26                     260               50   36               23   

  Absnt_hr_estimate  
0           2-4 hrs  
1           4-8 hrs  
2           4-8 hrs  
3           4-8 hrs  
4          8-24 hrs

In [16]:
df_m_1.to_csv('D:\iNeuron\Intership_1\Absenteeism_at_work_AAA\Model_intern_1.csv',index=False)

In [17]:
df_m_1.columns

Index(['R_code', 'Transportation expense', 'Office Distance', 'Age',
       'Body mass index', 'Absnt_hr_estimate'],
      dtype='object')

In [18]:
import joblib

In [19]:
from sklearn.compose import make_column_transformer

In [20]:
column_trans=make_column_transformer((OneHotEncoder(sparse=False),['R_code']),remainder='passthrough')

In [21]:
X=df_m_1.drop('Absnt_hr_estimate',axis=1)
X.head()

R_code  Transportation expense  Office Distance  Age  Body mass index
0      26                     289               36   33               30
1      26                     289               36   33               30
2      26                     235               11   37               29
3      26                     260               50   36               23
4      26                     260               50   36               23

In [22]:
X=column_trans.fit_transform(X)

In [23]:
column_trans.get_feature_names()

['onehotencoder__x0_0',
 'onehotencoder__x0_1',
 'onehotencoder__x0_2',
 'onehotencoder__x0_3',
 'onehotencoder__x0_4',
 'onehotencoder__x0_5',
 'onehotencoder__x0_6',
 'onehotencoder__x0_7',
 'onehotencoder__x0_8',
 'onehotencoder__x0_9',
 'onehotencoder__x0_10',
 'onehotencoder__x0_11',
 'onehotencoder__x0_12',
 'onehotencoder__x0_13',
 'onehotencoder__x0_14',
 'onehotencoder__x0_15',
 'onehotencoder__x0_16',
 'onehotencoder__x0_17',
 'onehotencoder__x0_18',
 'onehotencoder__x0_19',
 'onehotencoder__x0_21',
 'onehotencoder__x0_22',
 'onehotencoder__x0_23',
 'onehotencoder__x0_24',
 'onehotencoder__x0_25',
 'onehotencoder__x0_26',
 'onehotencoder__x0_27',
 'onehotencoder__x0_28',
 'Transportation expense',
 'Office Distance',
 'Age',
 'Body mass index']

In [24]:
X

array([[ 0.,  0.,  0., ..., 36., 33., 30.],
       [ 0.,  0.,  0., ..., 36., 33., 30.],
       [ 0.,  0.,  0., ..., 11., 37., 29.],
       ...,
       [ 0.,  0.,  0., ..., 22., 40., 22.],
       [ 0.,  0.,  0., ..., 16., 32., 25.],
       [ 0.,  0.,  0., ..., 22., 40., 22.]])

In [25]:
y=df_m_1.Absnt_hr_estimate

In [26]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier


In [27]:
cross_val_score(RandomForestClassifier(n_estimators=2000,random_state=42),X,y,cv=5)

array([0.2972973 , 0.62837838, 0.39189189, 0.25      , 0.25      ])

In [28]:
clf_rf=RandomForestClassifier(n_estimators=2000,random_state=42)

In [29]:
clf_rf.fit(X,y)

RandomForestClassifier(n_estimators=2000, random_state=42)

In [33]:
# creating a dataframe to test transform of one hot encoder
df_test=pd.DataFrame({'R_code':[26], 'Transportation expense':[289], 'Office Distance':[36],
       'Age':[33], 'Body mass index':[30]})

In [34]:
df_test.head()

R_code  Transportation expense  Office Distance  Age  Body mass index
0      26                     289               36   33               30

In [35]:
X_test=column_trans.transform(df_test)

In [36]:
clf_rf.predict(X_test)

array(['4-8 hrs'], dtype=object)

In [37]:
import joblib

In [38]:
joblib.dump(column_trans,'ohe_1.ml')

['ohe_1.ml']

In [39]:
ohe_loaded=joblib.load('ohe_1.ml')

In [40]:
ohe_loaded.transform(df_test)

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   1.,   0.,   0., 289.,  36.,  33.,  30.]])

In [41]:
clf_rf.predict(ohe_loaded.transform(df_test))

array(['4-8 hrs'], dtype=object)

In [42]:
from sklearn.pipeline import make_pipeline

In [43]:
pipe=make_pipeline(column_trans,clf_rf)

In [44]:
pipe.predict(df_test)

array(['4-8 hrs'], dtype=object)

In [45]:
joblib.dump(pipe,'pipe.ml')

['pipe.ml']

In [46]:
pipe_loaded=joblib.load('pipe.ml')

In [47]:
pipe_loaded.predict(df_test)

array(['4-8 hrs'], dtype=object)

In [48]:
import sklearn
print(sklearn.__version__)


0.23.1
